root = "."

[build]
cmd = "go build -o ${APP_PATH}/tmp/out cmd/*.go"
bin = "${APP_PATH}/tmp/out"
full_bin = "${APP_PATH}/tmp/out"
include_ext = ["go", "tpl", "tmpl", "html"]
# exclude_dir = ["tmp", "vendor"]
include_dir = ["internal", "cmd"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 2000 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
