version: '3.1'

services:

  mongo0:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /tmp/storage-system/db0:/data/db:rw
      - ./deployment/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  node0:
    build:
      network: host
      context: .
      dockerfile: deployment/go-services/Dockerfile
      args:
        SERVICE_NAME: "node"
    image: cc/node
    tty: true
    depends_on:
      - mongo0
    container_name: node0
    ports:
      - 8084:8080
    env_file:
      - node/.env

  data-access-api:
    build:
      network: host
      context: .
      dockerfile: deployment/go-services/Dockerfile
      args:
        SERVICE_NAME: "data-access-api"
    image: cc/data-access-api
    tty: true
    depends_on:
      - node0
    container_name: data-access-api
    ports:
      - 8085:8080
    env_file:
      - data-access-api/.env
